name: Build and Deploy Angular App
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
      - name: Install dependencies
        run: |
          npm install
      - name: Build Angular app
        run: |
          npm run build -- --configuration production
      - name: Archive production build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
  deploy:
    runs-on:
      - self-hosted
      - windows
    needs: build
    steps:
      - name: Download production build
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist
      - name: List contents of downloaded build directory (for debugging)
        run: |
          Get-ChildItem -Recurse ./dist
      - name: Create directory for TZApp in IIS path
        run: |
          if (!(Test-Path -Path "C:\web\TZApp")) {
            New-Item -Path "C:\web\TZApp" -ItemType Directory -Force
          }
      - name: Copy build files to IIS directory
        run: >
          Copy-Item -Path "./dist/TZApp/browser/*" -Destination "C:\web\TZApp"
          -Recurse -Force

      - name: Copy PowerShell script to server
        run: |
          
          $scriptPath = "$env:GITHUB_WORKSPACE\scripts\deploy-iis.ps1"
          $destinationPath = "C:\Temp\deploy-site.ps1" # Destination path on server

          
          Copy-Item -Path $scriptPath -Destination $destinationPath

      # Run the PowerShell script as an administrator
      - name: Run PowerShell script as administrator
        run: |
          
          $scriptPath = "C:\Temp\deploy-site.ps1"

          
          Start-Process -FilePath "powershell.exe" -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File $scriptPath" -Verb RunAs -Wait  
  
