name: Build and Deploy TZApp

# Trigger on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Angular App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Install Angular CLI
        run: npm install -g @angular/cli@18.2.12

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Create a GitHub Release and Upload Build Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to IIS
    runs-on: self-hosted

    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/github-cli.sh | sudo bash
          sudo apt-get install gh

      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}

      - name: Download Build Artifact from GitHub Release
        run: |
          gh release download <release_name> --repo <username>/<repo> --dir ./deploy

      - name: Ensure IIS Directory Exists and Deploy
        run: |
          # Define paths
          $iisPath = "C:\web\TZApp"
          $buildPath = "${{ github.workspace }}\deploy"  # Path where the artifact is downloaded

          # Ensure IIS directory exists
          if (!(Test-Path -Path $iisPath)) {
            New-Item -ItemType Directory -Force -Path $iisPath
          }

          # Clear old files
          Remove-Item -Recurse -Force "$iisPath\*"

          # Copy new files
          Copy-Item -Recurse -Force "$buildPath\*" $iisPath
        shell: pwsh
