name: Build and Deploy TZApp

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Angular App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Install Angular CLI
        run: npm install -g @angular/cli@18.2.12

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: angular-build
          path: dist/

  deploy:
    name: Deploy to IIS
    runs-on: self-hosted

    needs: build

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: angular-build

      - name: Deploy to IIS
        run: |
          # Ensure IIS directory exists
          if (!(Test-Path -Path 'C:\web\TZApp')) { 
            New-Item -ItemType Directory -Force -Path 'C:\web\TZApp' 
          }
          # Clear old files
          Remove-Item -Recurse -Force 'C:\web\TZApp\*'
          # Copy new files to IIS directory
          Copy-Item -Recurse -Force './dist/TZApp/*' 'C:\web\TZApp'
        shell: powershell
