name: Build and Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: |
          npm install

      - name: Build Angular app
        run: |
          npm run build -- --configuration production

      - name: Archive production build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  deploy:
    runs-on: [self-hosted, windows]
    needs: build
    steps:
      - name: Download production build
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist

      - name: List contents of downloaded build directory (for debugging)
        run: |
          Get-ChildItem -Recurse ./dist

      - name: Create directory for TZApp in IIS path
        run: |
          New-Item -Path "C:\web\TZApp" -ItemType Directory -Force

      - name: Copy build files to IIS directory
        run: |
          Copy-Item -Path "./dist/TZApp/*" -Destination "C:\web\TZApp" -Recurse -Force
        
      - name: Create IIS site
        run: |
            powershell -NoProfile -ExecutionPolicy Bypass -Command "
              try {
                  Import-Module WebAdministration
                  if (-not (Test-Path IIS:\Sites\TZApp)) {
                      New-Website -Name 'TZApp' -Port 80 -PhysicalPath 'C:\web\TZApp' -ApplicationPool 'DefaultAppPool'
                      Write-Output 'IIS site created successfully.'
                  } else {
                      Write-Output 'IIS site already exists.'
                  }
              } catch {
                  Write-Error 'Failed to create IIS site: $_'
                  exit 1
              }
            "
        
      - name: Start IIS site
        run: |
            powershell -NoProfile -ExecutionPolicy Bypass -Command "
              try {
                  Import-Module WebAdministration
                  Start-Website -Name 'TZApp'
                  Write-Output 'IIS site started successfully.'
              } catch {
                  Write-Error 'Failed to start IIS site: $_'
                  exit 1
              }
            "
          






